spring:
  redis:
    host: 123.57.54.10
    password:
    database: 2
    port: 6379
    timeout: 2s
    lettuce:
      pool:
        max-active: 100
        max-wait: 1000
        max-idle: 50
        min-idle: 0
      shutdown-timeout: 0
  cache:
    type: redis
